services:
  app:
    env_file: ".env"
    build: .
    networks:
      - tmod-network
    ports:
      - "${TERRARIA_PORT}:${TERRARIA_PORT}" # Terraria server port
    container_name: tmod-app
    volumes:
      - ./tmod_data:/root/.local/share/Terraria
networks:
  tmod-network:
    driver: bridge